package.json
utils/__tests__/config.test.ts

Remove definition generation

---

.devops/deploy-pipelines.yml
package.json
utils/__tests__/config.test.ts

Changed master brench reference with main
Add missing shx command in script for definition generation
Fixed no more used configuration decoder in test

[#IP432] Fix wrong main branch name and missing shx in script

---

.devops/deploy-pipelines.yml

[#IP-432] Fix deployment slot name

---

CosmosApiServicesImportEvent/__tests__/handler.messages.test.ts
CosmosApiServicesImportEvent/handler.messages.ts
utils/config.ts
utils/cosmosdb.ts
utils/types/reportTypes.ts

- Add logs
- Add content check
- Set cosmosdb preferred location

[#IC-134] Add checks and cosmosdb preferred location

---

CosmosApiServicesImportEvent/handler.messages.ts
utils/types/reportTypes.ts

[#IC-134] Add extra logs to message report

---

CosmosApiServicesImportEvent/handler.messages.ts
host.json

- Increase functions timeout
- Update logs

[#IC-134] Increase functions timeout

---

CosmosApiServicesImportEvent/index.ts

Disable message export command

---

CosmosApiServicesImportEvent/index.ts

restore process messages

---

CosmosApiServicesImportEvent/__tests__/handler.messages.test.ts
CosmosApiServicesImportEvent/handler.messages.ts
EnrichMessagesReportBlobTrigger/handler.ts
utils/AsyncIterableTask.ts

[IC-134]  fix duplicated values

---

CosmosApiServicesImportEvent/commands.ts
CosmosApiServicesImportEvent/handler.messages.ts
CosmosApiServicesImportEvent/index.ts
CreateMessageReportTimeTrigger/function.json
CreateMessageReportTimeTrigger/handler.ts
CreateMessageReportTimeTrigger/index.ts
package.json
utils/config.ts
yarn.lock

Add time trigger to export reports, based on an export list retrieved from the Table Storage

[#IC-134] Add new time trigger to export reports

---

CosmosApiServicesChangeFeed/function.json

Start from beginning - services

---

avro/message.json
utils/formatter/messagesAvroFormatter.ts

- Add new avro model for messages (and their contents)

[#IC-341] add message avro model

---

avro/notification-status.json
utils/formatter/notificationStatusAvroFormatter.ts

[#IC-343] add notificationStatus avro model

---

avro/message-status.json
utils/formatter/messageStatusAvroFormatter.ts

- Add message status avro model

[#IC-342] Add message status avro model

---

CosmosApiMessageStatusChangeFeed/function.json
CosmosApiMessageStatusChangeFeed/handler.ts
CosmosApiMessageStatusChangeFeed/index.ts
avro/message-status.json
local.settings.json.example
utils/config.ts
utils/formatter/messageStatusAvroFormatter.ts

This PR depends on https://github.com/pagopa/io-functions-elt/pull/35

[IC-352] add message-status trigger

---

host.json

Remove http default prefix config: the rest endpoint (only Info for now) should follow the standard path naming.
remove http config from host.json
Align enpoint path naming with our standard

Remove wrong http host.json config

---

.devops/deploy-pipelines.yml

Fix healthcheck stage

---

Info/function.json

Remove wrong 'api' prefix from Info function.json 
removed 'api' prefix
align path between function.json and index.ts

Fix info endpoint path

---

__mocks__/messages.mock.ts
avro/message.json
package.json
utils/formatter/messagesAvroFormatter.ts
yarn.lock

- add featureLevelType to message avro model
Advanced feature management
mock

[#IC-434]  add featureLevelType to message avro model

---

CODEOWNERS

Add Alessio and Giovanni to codeowners

---

AnalyticsServiceChangeFeedInboundProcessorAdapter/function.json
utils/config.ts

Refactor the analytics services processor inbound adapter to use the common lease collection instead of a dedicated collection for the change feed trigger.
see commit history
Normalize the legacy function to the current standard and re-publish all the services to PDND (due to missing services on PDND)
unit test
manual system test

Refactor services processor to use the common lease collection

---

README.md
local.settings.json.example

* [Fix local.settings.json.example to be a valid JSON](6eeaf283c3623e7e932da63e98a1c79ab5534ffc)
* [Update README to be aligned with local.settings.json](71f6533ebeb0ff30ca305615be586a6c076e899b) 
It seems like the `README.md` is not aligned with the `local.settings.json.example`, in fact the latest changes to the `README.md` are related to 2021, I believe it is more convenient to put the copy command for the `local.settings.json.example` instead of its content so we do not need to update it every time we update the example.

Fix readme

---

avro/service-preferences.json

* [[#IOPID-1917] added service-preferences avro file](https://github.com/pagopa/io-functions-elt/commit/cd74bdd86f4607515022a983f12285843760a8c2)
foundation schema for services-preferences send over event-hub topic
successfully generated typescript file with `generate:avro` script

[#IOPID-1917] added service-preferences avro file

---

avro/profile.json

* [[#IOPID-1916] added avro schema for profile](https://github.com/pagopa/io-functions-elt/commit/30198702b34b2e324eb5239992fa11e18450bad1)
foundation schema related to profile informations
locally generated a valid typescript file through `generate:avro` script

[#IOPID-1916] added avro schema for profile

---

AnalyticsMessageStatusChangeFeedInboundProcessorAdapter/function.json
AnalyticsMessagesChangeFeedInboundProcessorAdapter/function.json
AnalyticsServiceChangeFeedInboundProcessorAdapter/function.json
AnalyticsServicePreferencesChangeFeedInboundProcessorAdapter/function.json
CosmosApiMessageStatusChangeFeed/function.json
CosmosApiMessagesChangeFeed/function.json
CosmosApiServicesChangeFeed/function.json
host.json

* Update extension bundle following the [official guide](https://learn.microsoft.com/it-it/azure/azure-functions/migrate-cosmos-db-version-3-version-4?tabs=isolated-process&pivots=programming-language-javascript#changes-to-item-id-generation);
We need to update the bundle because of end of life on august 31.
Locally I have tested the cosmosdb change feed trigger before and after the migration.

deps: update extension bundle

---

CosmosApiServicesImportEvent/handler.messages.ts
EnrichMessagesReportBlobTrigger/function.json

rename blobTrigger path regex

---

avro/profile-deletion.json

Add profile-deletion avro schema
Send profile deletion event to PDND
build

[#IOPID-2201] Add `profile-deletion` avro schema

---

utils/config.ts

[#IOPID-2343] fix: config wrong decoder type
